/*
 * Copyright 2015-2017 Richard Linsdale.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.theretiredprogrammer.nbpcglibrary.authentication.dataobjects;

import java.io.IOException;
import java.util.List;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import uk.theretiredprogrammer.nbpcglibrary.common.Listener;
import uk.theretiredprogrammer.nbpcglibrary.common.LogBuilder;
import uk.theretiredprogrammer.nbpcglibrary.data.entity.*;
import uk.theretiredprogrammer.nbpcglibrary.data.entityreferences.*;

/**
 * The ApplicationRoot Object
 *
 * (Class generated by NetBeans Platform Code Generator tools using script.xml.
 * Do not edit this file. Apply any changes to the definition file and
 * regenerate all files.)
 *
 * @author Richard Linsdale (richard at theretiredprogrammer.uk)
 */
@ServiceProvider(service = ApplicationRoot.class)
public class ApplicationRoot extends CoreEntity {

    /**
     * the ApplicationRoot field identifiers
     */
    public enum ApplicationRootField {
        /**
         * the applications collection
         */
        APPLICATIONS,
    }
    
    private final EntityReferenceSet<Integer, Application, ApplicationRoot> applications;
    
    @Override
    public final String instanceDescription() {
        return LogBuilder.instanceDescription(this);
    }

    /**
     * Get the ApplicationRoot entity.
     *
     * @return the ApplicationRoot entity
     */
    public static ApplicationRoot get() {
        return Lookup.getDefault().lookup(ApplicationRoot.class);
    }

    /**
     * Constructor.
     *
     * @throws IOException if problem with obtaining/parsing data
     */
    public ApplicationRoot() throws IOException {
        super("ApplicationRoot", "folder_table");
        applications = new EntityReferenceSet<>(instanceDescription() + ">Applications", Application.EM.class);
        applications.load();
    }

    /**
     * Add a Application to the root's list
     *
     * @param e the application
     */
    public void addApplication(Application e) {
        applications.add(e);
    }

    /**
     * Remove a Application from the root's list
     *
     * @param e the Application
     */
    public void removeApplication(Application e) {
        applications.remove(e);
    }

    /**
     * Add set listener to applications collections
     *
     * @param listener the set change listener to add
     */
    public void addApplicationSetChangeListener(Listener<SetChangeEventParams> listener) {
        applications.addSetListener(listener);
    }

    /**
     * remove set listener to applications collections
     *
     * @param listener the set change listener to add
     */
    public void removeApplicationSetChangeListener(Listener<SetChangeEventParams> listener) {
        applications.removeSetListener(listener);
    }

    /**
     * Add set listener to requested collection field (set)
     *
     * @param listener the set change listener to be added
     */
    public static void addApplicationsSetChangeListeners(Listener<SetChangeEventParams> listener) {
        get().applications.addSetListener(listener);
    }

    /**
     * Remove set listener from requested collection field (set)
     *
     * @param listener the set change listener to be removed
     */
    public static void removeApplicationsSetChangeListeners(Listener<SetChangeEventParams> listener) {
        get().applications.removeSetListener(listener);
    }

    /**
     * Get the list of Applications
     *
     * @return the list of Applications
     */
    public List<Application> getApplications() {        
        return applications.get();
    }
    
    @Override
    protected final void entityRestoreState() {
        applications.restoreState();
    }
    
    @Override
    public String getDisplayName() {
        return "Applications";
    }
}
