/*
 * Copyright 2015-2017 Richard Linsdale.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.theretiredprogrammer.nbpcglibrary.authentication.dataobjects;

import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import org.openide.util.Lookup;
import org.openide.util.lookup.ServiceProvider;
import static uk.theretiredprogrammer.nbpcglibrary.authentication.dataobjects.Permission.PermissionField;
import uk.theretiredprogrammer.nbpcglibrary.api.*;
import uk.theretiredprogrammer.nbpcglibrary.common.*;
import uk.theretiredprogrammer.nbpcglibrary.data.entity.*;
import uk.theretiredprogrammer.nbpcglibrary.data.entityreferences.*;

/**
 * The Permission Entity.
 *
 * (Class generated by NetBeans Platform Code Generator tools using script.xml.
 * Do not edit this file. Apply any changes to the definition file and
 * regenerate all files.)
 *
 * @author Richard Linsdale (richard at theretiredprogrammer.uk)
 */
public class Permission extends Entity<Integer, Permission, Application, PermissionField> {

    /**
     * the Permission field identifiers
     */
    public enum PermissionField {
        /**
         * the permission field
         */
        PERMISSION,
        /**
         * the application field
         */
        APPLICATION,
    }
    
    private final Rules entityRules = new Rules();
    private String permission = "";
    private String permissionOriginal;
    private final Rules permissionRules = new Rules();
    private final EntityReference<Integer, Application, ApplicationRoot> application;
    private final Rules applicationRules = new Rules();
    private int id = 0;
    private String createdby = "";
    private final Timestamp createdon = new Timestamp();
    private String updatedby = "";
    private final Timestamp updatedon = new Timestamp();

    /**
     * Constructor - Permission.
     *
     * @param id the unique id for this entity
     * @param em - the entity manager for this entity type
     */
    public Permission(int id, Permission.EM em) {
        super("Permission[" + Integer.toString(id) + "]", "thumb_up", em);
        this.id = id;
        application = new EntityReference<>("Permission>Application", Application.getEM(), new ReferencedEntityTitleChangeListener("Permission>Application"));
        addRule(applicationRules, application.getDefinedRule());
        addRule(permissionRules, new PermissionMinRule());
        addRule(permissionRules, new PermissionMaxRule());
        checkRulesAtLoad(new StringBuilder());
    }
    
    @Override
    public boolean isPersistent() {
        return id > 0;
    }
    
    @Override
    public final Integer getPK() {
        return getId();
    }

    /**
     * Get all rules for this entity
     *
     * @return the set of rules
     */
    public final Rules getEntityRules() {
        return entityRules;
    }
    
    @Override
    public final String instanceDescription() {
        return "".equals(permission)
                ? LogBuilder.instanceDescription(this, Integer.toString(getId()))
                : LogBuilder.instanceDescription(this, Integer.toString(getId()) + "-" + permission);
    }
    
    private class PermissionMinRule extends Rule {
        
        public PermissionMinRule() {
            super("Too short");
        }
        
        @Override
        public boolean ruleCheck() {
            return permission.length() >= 1;
        }
    }
    
    private class PermissionMaxRule extends Rule {
        
        public PermissionMaxRule() {
            super("Too long");
        }
        
        @Override
        public boolean ruleCheck() {
            return permission.length() <= 100;
        }
    }

    /**
     * Get the permission field rules.
     *
     * @return the rules
     */
    public Rules getPermissionRules() {
        return permissionRules;
    }

    /**
     * Get the permission.
     *
     * @return the permission
     */
    public final String getPermission() {
        return permission;
    }

    /**
     * Define the Permission.
     *
     * @param permission the permission
     */
    public void setPermission(String permission) {
        if (!this.permission.equals(permission)) {
            ensureEditing();
            this.permission = permission;
            fireFieldChange(PermissionField.PERMISSION);
            fireNameAndOrTitleChangeOnPermission();
        }
    }

    private void fireNameAndOrTitleChangeOnPermission() {
        nameListenerFire();
        titleListenerFire();
    }

    /**
     * Get the application field rules.
     *
     * @return the rules
     */
    public Rules getApplicationRules() {
        return applicationRules;
    }

    /**
     * Get the parent Entity associated with this entity.
     *
     * @return the Application entity
     */
    public Application getParent() {
        return application.get();
    }

    /**
     * Set the parent (Application) Entity associated with this entity. Called
     * from the parent entity as part of the addPermission method
     *
     * @param e the parent application entity
     */
    protected void linkToParent(Application e) {
        ensureEditing();
        if (application.set(e)) {
            fireFieldChange(PermissionField.APPLICATION);
            fireNameAndOrTitleChangeOnApplication();
        }
    }

    /**
     * Clear the parent (Application) Entity associated with this entity. Called
     * from the parent entity as part of the removePermission method
     */
    protected void unlinkFromParent() {
        ensureEditing();
        if (application.set()) {
            fireFieldChange(PermissionField.APPLICATION);
            fireNameAndOrTitleChangeOnApplication();
        }
    }

    private void fireNameAndOrTitleChangeOnApplication() {
        titleListenerFire();
    }

    /**
     * Get the id.
     *
     * @return the id
     */
    public final int getId() {
        return id;
    }

    /**
     * Get the createdby.
     *
     * @return the createdby
     */
    public final String getCreatedby() {
        return createdby;
    }

    /**
     * Get the createdon.
     *
     * @return the createdon
     */
    public final Timestamp getCreatedon() {
        return createdon;
    }

    /**
     * Get the updatedby.
     *
     * @return the updatedby
     */
    public final String getUpdatedby() {
        return updatedby;
    }

    /**
     * Get the updatedon.
     *
     * @return the updatedon
     */
    public final Timestamp getUpdatedon() {
        return updatedon;
    }
    
    @Override
    protected final void entitySaveState() {
        permissionOriginal = permission;
        application.saveState();
    }
    
    @Override
    protected final void entityRestoreState() {
        permission = permissionOriginal;
        application.restoreState();
    }
    
    @Override
    protected final void entityRemove() {
        {
            Userpermission.EM em = Userpermission.getEM();
            em.getEntityPersistenceProvider().find("permission", getPK()).stream().forEach((pk) -> {
                em.get(pk).remove();
            });
        }
        getParent().removePermission(this);
    }
    
    @Override
    protected final void entityLoad(EntityFields data) {
        permission = (String) data.get("permission");
        application.set((Integer) data.get("application"));
        id = (Integer) data.get("id");
        createdby = (String) data.get("createdby");
        try {
            createdon.setDateUsingSQLString((String) data.get("createdon"));
        } catch (BadFormatException ex) {
            throw new LogicException("Load reported bad Timestamp format - should never happen!!");
        }
        updatedby = (String) data.get("updatedby");
        try {
            updatedon.setDateUsingSQLString((String) data.get("updatedon"));
        } catch (BadFormatException ex) {
            throw new LogicException("Load reported bad Timestamp format - should never happen!!");
        }
    }
    
    @Override
    protected final void entityCopy(Permission from) {
        permission = from.getPermission();
    }
    
    @Override
    protected final boolean entityDiffs(EntityFields data) {
        if (!permission.equals(permissionOriginal)) {
            data.put("permission", permission);
        }
        if (application.isDirty()) {
            int idrefApplication = application.getPK();
            if (idrefApplication < 0) {
                application.get().save(new StringBuilder());
                idrefApplication = application.get().getPK();
                if (idrefApplication < 0) {
                    return false;
                }
            }
            data.put("application", idrefApplication);
        }
        return true;
    }
    
    @Override
    protected final boolean entityValues(EntityFields data) {
        data.put("permission", permission);
        int idrefApplication = application.getPK();
        if (idrefApplication < 0) {
            application.get().save(new StringBuilder());
            idrefApplication = application.get().getPK();
            if (idrefApplication < 0) {
                return false;
            }
        }
        data.put("application", idrefApplication);
        return true;
    }

    /**
     * Get the Permission Entity Manager
     *
     * @return the Permission Entity Manager
     */
    public static Permission.EM getEM() {
        return Lookup.getDefault().lookup(Permission.EM.class);
    }

    /**
     * The Permission Entity Manager
     */
    @ServiceProvider(service = Permission.EM.class)
    public static class EM extends EntityManager<Integer, Permission, Application> {
        
        private static int tpk = -1;

        /**
         * Constructor.
         */
        public EM() {
            super("Permission");
        }
        
        @Override
        protected final void link2parent(Permission e, Application parent) {
            parent.addPermission(e);
        }
        
        @Override
        protected final Permission createNewEntity() {
            return new Permission(tpk--, this);
        }
        
        @Override
        protected final Permission createNewEntity(Integer pk) {
            return new Permission(pk, this);
        }
        
        @Override
        protected final EntityPersistenceProvider createEntityPersistenceProvider() {
            return EntityPersistenceProviderManager.getEntityPersistenceProvider("authentication", "Permission");
        }
        
        @Override
        protected boolean isPersistent(Integer pkey) {
            return pkey > 0;
        }
    }

    /**
     * Get the set of all Permissions.
     *
     * @return the set of all Permissions
     */
    public static List<Permission> getAllPermissions() {
        List<Permission> list = new ArrayList<>();
        Application.getAllApplications().stream()
                .forEach(parent -> list.addAll(parent.getPermissions()));
        return list;
    }
    
    @Override
    public String getDisplayName() {
        return MessageFormat.format("{0}", formatPermission());
    }
    
    @Override
    public String getDisplayTitle() {
        return MessageFormat.format("{0} for {1}", formatPermission(), formatApplication());
    }
    
    @Override
    public String getSortKey() {
        return getDisplayTitle();
    }

    /**
     * Get the formatted text version of permission field
     *
     * @return the formatted String
     */
    public String formatPermission() {
        return getPermission();
    }

    /**
     * Get the formatted text version of application field
     *
     * @return the formatted String
     */
    public String formatApplication() {
        return getParent() != null ? getParent().getDisplayName() : "undefined";
    }

    /**
     * Get the formatted text version of id field
     *
     * @return the formatted String
     */
    public String formatId() {
        return Integer.toString(getId());
    }

    /**
     * Get the formatted text version of createdby field
     *
     * @return the formatted String
     */
    public String formatCreatedby() {
        return getCreatedby();
    }

    /**
     * Get the formatted text version of createdon field
     *
     * @return the formatted String
     */
    public String formatCreatedon() {
        return getCreatedon().toString();
    }

    /**
     * Get the formatted text version of updatedby field
     *
     * @return the formatted String
     */
    public String formatUpdatedby() {
        return getUpdatedby();
    }

    /**
     * Get the formatted text version of updatedon field
     *
     * @return the formatted String
     */
    public String formatUpdatedon() {
        return getUpdatedon().toString();
    }

    /**
     * Get the formatted text version of permission field left padded with zeros
     * if less than minimum size.
     *
     * @param minChars minimum size
     * @return the formatted String
     */
    public String formatPermission(int minChars) {
        return StringX.padLeftIfInt(formatPermission(), minChars, '0');
    }

    /**
     * Get the formatted text version of id field left padded with zeros if less
     * than minimum size.
     *
     * @param minDigits minimum size
     * @return the formatted String
     */
    public String formatId(int minDigits) {
        return StringX.padLeft(formatId(), minDigits, '0');
    }

    /**
     * Get the formatted text version of createdby field left padded with zeros
     * if less than minimum size.
     *
     * @param minChars minimum size
     * @return the formatted String
     */
    public String formatCreatedby(int minChars) {
        return StringX.padLeftIfInt(formatCreatedby(), minChars, '0');
    }

    /**
     * Get the formatted text version of updatedby field left padded with zeros
     * if less than minimum size.
     *
     * @param minChars minimum size
     * @return the formatted String
     */
    public String formatUpdatedby(int minChars) {
        return StringX.padLeftIfInt(formatUpdatedby(), minChars, '0');
    }
    
    private class ReferencedEntityTitleChangeListener extends Listener<SimpleEventParams> {
        
        public ReferencedEntityTitleChangeListener(String name) {
            super(name);
        }
        
        @Override
        public void action(SimpleEventParams p) {
            titleListenerFire();
        }
    }
}
