--
-- Copyright (C) 2014-2016 Richard Linsdale (richard at theretiredprogrammer.uk)
--
-- This library is free software; you can redistribute it and/or
-- modify it under the terms of the GNU Lesser General Public
-- License as published by the Free Software Foundation; either
-- version 2.1 of the License, or (at your option) any later version.
--
-- This library is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
-- Lesser General Public License for more details.
--
-- You should have received a copy of the GNU Lesser General Public
-- License along with this library; if not, write to the Free Software
-- Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
-- MA 02110-1301  USA
--
--
-- CREATE TABLES & INSERTS
--
-- Script generated by NetBeans Platform Code Generator tools using script.xml. 
-- Do not edit this file.  Apply any changes to the definition file and
-- regenerate all files.
--
-- @package generated-scripts
-- @author Richard Linsdale (richard at theretiredprogrammer.uk)
--
DROP DATABASE IF EXISTS authentication2;
CREATE DATABASE authentication2 CHARACTER SET utf8 COLLATE utf8_bin;
USE authentication2;
--
CREATE TABLE User(
    username  VARCHAR(100) UNIQUE NOT NULL
    ,encodedpassword  CHAR(40)  NOT NULL
    ,usercode  CHAR(4) UNIQUE NOT NULL
    ,enabled  BOOLEAN  NOT NULL
    ,id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    ,createdby CHAR(4) NOT NULL
    ,createdon CHAR(14) NOT NULL
    ,updatedby CHAR(4) NOT NULL
    ,updatedon CHAR(14) NOT NULL
) ENGINE = INNODB;

INSERT INTO User (
    username
    ,encodedpassword
    ,usercode
    ,enabled
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'richard'
    ,'ea27671eaac43ca1ecb782b7c9e9344a82b0702d'
    ,'rl12'
    ,true
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

CREATE TABLE Application(
    application  VARCHAR(100) UNIQUE NOT NULL
    ,id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    ,createdby CHAR(4) NOT NULL
    ,createdon CHAR(14) NOT NULL
    ,updatedby CHAR(4) NOT NULL
    ,updatedon CHAR(14) NOT NULL
) ENGINE = INNODB;

INSERT INTO Application (
    application
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'accesscontrolmanager'
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

INSERT INTO Application (
    application
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'photogallery'
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

INSERT INTO Application (
    application
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'marktimingsrecorder'
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

CREATE TABLE Role(
    role  VARCHAR(100)  NOT NULL
    ,application MEDIUMINT UNSIGNED NOT NULL ,FOREIGN KEY (application) REFERENCES Application(id)
    ,id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    ,createdby CHAR(4) NOT NULL
    ,createdon CHAR(14) NOT NULL
    ,updatedby CHAR(4) NOT NULL
    ,updatedon CHAR(14) NOT NULL
) ENGINE = INNODB;

INSERT INTO Role (
    role
    ,application
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'Manager'
    ,1
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

INSERT INTO Role (
    role
    ,application
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'Manager'
    ,2
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

INSERT INTO Role (
    role
    ,application
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    'Coach'
    ,3
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

CREATE TABLE Permission(
    permission  VARCHAR(100)  NOT NULL
    ,application MEDIUMINT UNSIGNED NOT NULL ,FOREIGN KEY (application) REFERENCES Application(id)
    ,id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    ,createdby CHAR(4) NOT NULL
    ,createdon CHAR(14) NOT NULL
    ,updatedby CHAR(4) NOT NULL
    ,updatedon CHAR(14) NOT NULL
) ENGINE = INNODB;

CREATE TABLE Userrole(
    role  MEDIUMINT UNSIGNED  NOT NULL ,FOREIGN KEY (role) REFERENCES Role(id)
    ,user MEDIUMINT UNSIGNED NOT NULL ,FOREIGN KEY (user) REFERENCES User(id)
    ,id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    ,createdby CHAR(4) NOT NULL
    ,createdon CHAR(14) NOT NULL
    ,updatedby CHAR(4) NOT NULL
    ,updatedon CHAR(14) NOT NULL
) ENGINE = INNODB;

INSERT INTO Userrole (
    role
    ,user
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    1
    ,1
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

INSERT INTO Userrole (
    role
    ,user
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    2
    ,1
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

INSERT INTO Userrole (
    role
    ,user
    ,createdby
    ,createdon
    ,updatedby
    ,updatedon
)
VALUES (
    3
    ,1
    ,'nbcg'
    ,'20160627204229'
    ,'nbcg'
    ,'20160627204229'
);

CREATE TABLE Userpermission(
    permission  MEDIUMINT UNSIGNED  NOT NULL ,FOREIGN KEY (permission) REFERENCES Permission(id)
    ,user MEDIUMINT UNSIGNED NOT NULL ,FOREIGN KEY (user) REFERENCES User(id)
    ,id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
    ,createdby CHAR(4) NOT NULL
    ,createdon CHAR(14) NOT NULL
    ,updatedby CHAR(4) NOT NULL
    ,updatedon CHAR(14) NOT NULL
) ENGINE = INNODB;

